itech_formulaire:
    resource: "@ItechFormulaireBundle/Controller/"
    type:     annotation
    prefix:   /
    
acme_website: 
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix:   / 

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"